apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      serviceAccountName: jenkins
      containers:
        - name: boardgame
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: boardgame
