apiVersion: v1
kind: Secret
metadata:
  name: boardgame
  namespace: webapps
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ZXlKd1lYbHNiMkZrSWpvaVNsazBXSFJ3TWtKWFR6RnFOREY1YUU1RmVGQnBMekJGUlVaQ01UbElZ
MEkxWkRNeFUzWnpVMkZWVDNNMWQxbHphbEZSUVc4NWRubEpVR05RTkZaUFFsWmxlREJxTWpNelZH
Rm9TVGRLVTI0d2VGQlhOak5KTkRZeFJsUXZXVWRJUjFOMWQyOVJjVEp3Tm14dk5EaGtTRUptV0c4
NEt6RmxURGxGY2xKeFJVUlVVM1JuZEU1YVpWcHdRamx2YlRaT2RYaGFURXRQTTI5b2JVcFNjWGd3
VUZoVmQzQkNSRWxsVEZwdEsyNHdLMU5NVFRaSVdGY3dhRWxNZEhCSmNuVjJNMUphUkRoalYxVXha
SFJSUWk4MVJXTmtWWHBMTURKeGRIVjRZUzlsU0ZsWFJEQXhkbU0wZGtjd2FFNHJabmg1YzB0Q1kx
RlZRalpOVUhwWGEwVktaRzVaYVZBek1IbE5jRlJHTUUwM1Z6TXhUbTlUYUV4b1FrdFFhbkZrY0ZS
UFlUY3liWFk0UmxOYVIycHBZekp3YXl0SVltSnlZbFYwZDFaR1ZFVnRjVmR5VnpSelF6WmlOV2Ny
TWpBekwzVkJaRUpZUW10emRFRjZla1ZQWjBWemVYaHJSM1FyWVVkbkwzbG9UbXBaY0V4TWRETlFO
bTlzTHpWSVYyNVZabmt2VTFwUVFrZHZka292WTNsaWF6QXZWbFJhSzFoM04ydFBUMDVKTTFCcmJu
WTRjM0JQVmpoYVIzWXZka0pUUkZwTVRXUmFkSGRyTTJsUFVrNDVPRTFxTkN0SloxSXpUa2N2TDBa
NFVtTktPR0pvTkZWeFRsbzBWMXBDVkUwMGJFZHJORXRzUm5FNUwxZEtVVzVEU0V4T2NIRlZNMU1y
VDNSNFFYSmpZVmxKYVdnMGNTczVVWE5zY2toS1ExbGlkQzh4ZHpKaVlWZFhWbHBITW10M2VGZE1h
VVZVWjNwNVpXY3pSbUpaYTJ0cFVHNTBaRGg2ZWxseVN6ZGllbUZqYmtWVFRVSkNVRU5SZEhJNWQy
UmxNMjQzWVdnM2NHNDRRM1V2UmtSNmFuWk5SbUkyVVUxcllpc3hTa0ZTU25CT2FYcEpjVXQyT1RG
UlJVTkNOMFJ1TTFaTGNHdEhhelp6VVVseFdWTnNWWEJ5TUdOdVlsUTRSV2hLV1RWV2VXWnJkWHAy
VDFnemNsRlRaa3huVkVOT1pIVk5SR2xuTDBwUlVWWnZZMXBTYkZWU1ZYQmtSRVF6TkVWaUsyZDZh
R2d3T1RkdU0yRnRSM1UwTVVOcWIyd3llVVpDZEc4MVdVTnlTR3BqVUdZemVteHZRMkZKVFZKRGRs
QnRkV2hqVVVKS05HWlNkMlV5WVZKaWNtNHJibU00U0hoRlYwdFVVbWxMZUVFNFIzQnhObGR1Y25V
d00yNWpaSGhPYzJONFVGaExhR05DVFZKTFFYSjJUV05yVjFkM1VtNVdPSE5oYURnMlZUQktRM0Zo
VmxaUFpGUTNjekUzUjFOeFV6UmxZa3RDWlUxTk9GSkJhMDlvVGpsSlNVUjZjazAxY2sxWldEaEVO
bXBCWXpBd0sxTkZkblpCY201TlZFVlZVMDQ0Y1U0clRrMU1PRlU0UWpKV1ozVlNZMlYwUlZOTmVG
TnVaVmhSTDBKRWEwdzFWSEZ0ZWtWb1RuRkxhakZQVkdwNmF6WTBPVVJRVmtnelExUlBaMWxaYlha
dlluWnpkM0ExVGsxYUx6QTViVlZYVW1kTFYzbG5Va0pUVGtsR1RXUlFValZLVVZCRVdrVlhjVVZT
V1ZRdldpdFVXRlF3WlRKS2RrNHZiemhoUzI1MVJGTnRWblZyYUNzemJrVlZQU0lzSW1SaGRHRnJa
WGtpT2lKQlVVbENRVWhwU0ZkaFdWUnVVbFZYUTJKdWVpczNUSFpOUnl0QlVIWlVTSHBJYkVKVlVU
bEdjVVZ0VmpJMlFtUjNkMGRQTDA0d1VYQjRNVkJLTDNjMVVsSkZNa05SVG5SQlFVRkJabXBDT0VK
bmEzRm9hMmxIT1hjd1FrSjNZV2RpZWtKMFFXZEZRVTFIWjBkRFUzRkhVMGxpTTBSUlJVaEJWRUZs
UW1kc1oyaHJaMEphVVUxRlFWTTBkMFZSVVUxcGFHUkZlRTVDUVU1cmFGRm1UVEIxUVdkRlVXZEVk
bVJwZDI4NWREVnBRV2xyUm5KVWRVRlZPWGg1YzFsc2FXNWtTMUk1VUVJeVltOURSamxITDNaUFZt
eFpTVkEwVEhka01GaDRZa0ZSWlRaMVJYa3ZkUzlVVTBzeU1HRlFkV05NVnk4ME5tYzlQU0lzSW5a
bGNuTnBiMjRpT2lJeUlpd2lkSGx3WlNJNklrUkJWRUZmUzBWWklpd2laWGh3YVhKaGRHbHZiaUk2
TVRjeE1qYzRNVE14TlgwPQo=
